"""LLM-powered domain generation using the Databricks Foundation Model API."""

from __future__ import annotations

import json
import logging
import re
from dataclasses import asdict, dataclass, field
from typing import Any

from .config import DEFAULT_LLM_ENDPOINT, LLM_MAX_RETRIES, LLM_MAX_TOKENS, LLM_MAX_TOKENS_CAP, LLM_TEMPERATURE, LLM_TIMEOUT_SECONDS
from .genie import _api_request, _default_workspace_client
from .validators import sanitize_sql_identifier

_logger = logging.getLogger("genie_factory")


# ---------------------------------------------------------------------------
# Domain spec dataclasses
# ---------------------------------------------------------------------------


@dataclass
class ColumnSpec:
    name: str
    sql_type: str
    comment: str
    is_dimension: bool
    generation_expr: str


@dataclass
class TableSpec:
    table_name: str
    description: str
    columns: list[ColumnSpec]
    seasonal_patterns: dict
    entity_dimension: str
    dimension_values: list[dict]
    category_distribution: dict


@dataclass
class MetricViewSpec:
    view_name: str
    source_table: str
    dimensions: list[dict]
    measures: list[dict]


@dataclass
class ExampleSQL:
    question: str
    sql_lines: list[str]


@dataclass
class SQLSnippets:
    filters: list[dict]
    expressions: list[dict]
    measures: list[dict]


@dataclass
class BenchmarkSpec:
    question: str
    sql_lines: list[str]


@dataclass
class DomainSpec:
    """Complete domain specification generated by LLM."""

    company_name: str
    industry: str
    use_case: str
    space_title: str
    space_description: str
    schema_basename: str

    tables: list[TableSpec]
    metric_views: list[MetricViewSpec]

    genie_instructions: str
    sample_questions: list[str]
    example_sqls: list[ExampleSQL]
    sql_snippets: SQLSnippets
    benchmarks: list[BenchmarkSpec]

    def to_dict(self) -> dict:
        """Serialize to a plain dict suitable for JSON storage."""
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "DomainSpec":
        """Reconstruct a DomainSpec from a plain dict (e.g. loaded from JSON)."""
        return cls(
            company_name=d["company_name"],
            industry=d["industry"],
            use_case=d["use_case"],
            space_title=d["space_title"],
            space_description=d["space_description"],
            schema_basename=d["schema_basename"],
            tables=[
                TableSpec(
                    table_name=t["table_name"],
                    description=t["description"],
                    columns=[ColumnSpec(**c) for c in t["columns"]],
                    seasonal_patterns=t.get("seasonal_patterns", {}),
                    entity_dimension=t.get("entity_dimension", "transaction"),
                    dimension_values=t.get("dimension_values", []),
                    category_distribution=t.get("category_distribution", {}),
                )
                for t in d["tables"]
            ],
            metric_views=[MetricViewSpec(**mv) for mv in d["metric_views"]],
            genie_instructions=d["genie_instructions"],
            sample_questions=d["sample_questions"],
            example_sqls=[ExampleSQL(**e) for e in d["example_sqls"]],
            sql_snippets=SQLSnippets(**d["sql_snippets"]),
            benchmarks=[BenchmarkSpec(**b) for b in d["benchmarks"]],
        )


# ---------------------------------------------------------------------------
# LLM prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are a data modeling expert that generates complete domain specifications for \
Databricks Genie spaces. You produce structured JSON that drives synthetic data \
generation, metric view creation, and Genie space configuration.

You must return ONLY valid JSON matching the schema described in the user message. \
No markdown, no code fences, no explanation — just the JSON object."""

USER_PROMPT_TEMPLATE = """\
Generate a complete domain specification for a Databricks Genie space.

## Business Context
- **Industry:** {industry}
- **Company:** {company_name}
- **Use Case:** {use_case}
- **Context:** {business_context}

## Constraints
- Generate exactly {num_tables} tables
- Generate exactly {num_products} entity items (e.g., products, patients, assets) \
spread across 4-5 categories
- Generate exactly {num_locations} locations/facilities/sites spread across regions
- Each table must have 8-12 columns
- Each table gets one metric view with 4-6 measures
- Generate exactly 7 sample_questions, 7 example_sqls, 7 benchmarks
- SQL snippets: exactly 3 filters, 3 expressions, 4 measures
- Exactly 4 of the 7 example_sqls must use MEASURE() syntax against metric views; \
the remaining 3 must query base tables directly (one per table archetype: transaction, snapshot, forecast)
- Exactly 4 of the 7 benchmarks must use MEASURE() syntax; \
the remaining 3 must query base tables directly (one per table archetype)
- Plain table queries should use standard aggregations (COUNT, SUM, AVG), GROUP BY, \
WHERE filters, ORDER BY, or LIMIT — exercising each table's columns
- All SQL must be Databricks SQL compatible
- Table names must be valid SQL identifiers (lowercase, underscores only)
- The schema_basename must be a short lowercase identifier (no spaces)

## Table Archetypes
The {num_tables} tables should follow these archetypes (adapt names to the domain):
1. **Transaction table** — daily event records (orders, encounters, tickets, etc.). \
entity_dimension = "transaction". Columns should include an ID, date, entity references, \
quantities, amounts, and a status field with 3-4 possible values.
2. **Snapshot table** — periodic status snapshots (inventory levels, bed utilization, \
asset health, etc.). entity_dimension = "snapshot". Taken at weekly intervals.
3. **Forecast table** — predictions vs actuals (demand forecasts, readmission \
predictions, etc.). entity_dimension = "forecast". Monthly granularity with \
model_version field (v3.0, v3.1, v3.2).

## Column Generation Expressions
Each column needs a `generation_expr` — a SQL expression that produces the column \
value from the skeleton CTE. Available variables in expressions:
- `e.<any_entity_field>` — entity dimension columns (use the exact key names from dimension_values)
- `d.dt` — the date column from the date range
- `{{qty_noise}}` — deterministic random decimal [0,1) for quantities
- `{{status_noise}}` — deterministic random decimal [0,1) for status assignment
- `{{id_seq}}` — deterministic integer 0-499 for ID generation
- `{{seed}}` — the seed integer
- `ROW_NUMBER() OVER (ORDER BY d.dt, e.<pk>)` — for sequential IDs
- `MONTH(d.dt)`, `DAYOFWEEK(d.dt)` — date functions

For columns that come directly from the entity dimension, set generation_expr to \
empty string "" and the system will use `e.<column_name>`.

### CRITICAL CONSTRAINTS for generation_expr:
1. generation_expr runs PER ROW — NEVER use aggregate functions \
(SUM, COUNT, AVG, MIN, MAX, STDDEV, VARIANCE). These will cause SQL errors.
2. You may ONLY reference columns that exist in the skeleton CTE: \
entity dimension fields (by their exact key names from dimension_values), \
dt, mo, qty_noise, status_noise, select_noise, id_seq.
3. NEVER reference columns from other tables in the domain.
4. For columns that come from entities, ALWAYS use empty string "" — \
do NOT write the entity field name as the expression.
5. The d. and e. prefixes are allowed and will be automatically stripped. \
Use bare column names or e./d. prefixed names.

## Seasonal Patterns Format
seasonal_patterns is a dict where keys are category names and values are dicts \
mapping month numbers (as strings) to selection probabilities. Example:
{{"Electronics": {{"11,12": 0.06, "6,7": 0.015}}, "Food": {{"5,6,7": 0.045}}}}

category_distribution is a dict mapping category names to their default (non-seasonal) \
selection probability. Example:
{{"Electronics": 0.025, "Food": 0.035}}

## Metric View Measures
- Each measure expr must contain EXACTLY ONE aggregate function call (e.g., SUM(col), COUNT(DISTINCT col))
- NEVER nest aggregate functions: SUM(SUM(x)) or AVG(COUNT(x)) are INVALID
- NEVER combine multiple aggregates in one measure: SUM(x) / COUNT(y) is INVALID
- For ratio metrics, create SEPARATE measures for numerator and denominator (e.g., \
"delivered_order_count" = COUNT(DISTINCT CASE WHEN status='Delivered' THEN id END) and \
"total_order_count" = COUNT(DISTINCT id)). Genie can compute the ratio from separate measures.
- FILTER (WHERE ...) clauses on aggregates are allowed and encouraged

## SQL in example_sqls and benchmarks
- Use {{fqn}} as a placeholder for the fully-qualified schema name (e.g., catalog.schema)
- SQL should be broken into lines as a list of strings
- MEASURE() queries must reference the metric view name, not the base table
- MEASURE() queries should use GROUP BY ALL

## Few-Shot Example (Demand Forecasting Domain)
Here is a partial example of the expected output for a logistics/supply chain use case:

```json
{{
  "company_name": "NorthStar Logistics",
  "industry": "Logistics",
  "use_case": "Demand forecasting and inventory management",
  "space_title": "Northstar Logistics - Demand Forecasting & Inventory \\ud83d\\ude9b",
  "space_description": "Supply chain analytics for NorthStar Logistics. Ask questions about demand forecasts, inventory levels, stockout risks, fill rates, and shipment trends across 20 products and 8 distribution centers.",
  "schema_basename": "demand_forecasting",
  "tables": [
    {{
      "table_name": "shipment_orders",
      "description": "Daily shipment order history with delivered units, warehouse origins, destination regions, and order outcomes.",
      "columns": [
        {{"name": "order_id", "sql_type": "STRING", "comment": "Unique order identifier", "is_dimension": false, "generation_expr": "CONCAT('ORD-', LPAD(CAST(ROW_NUMBER() OVER (ORDER BY d.dt, e.sku) + 10000 AS STRING), 6, '0'))"}},
        {{"name": "order_date", "sql_type": "DATE", "comment": "Date order was placed", "is_dimension": true, "generation_expr": "d.dt"}},
        {{"name": "product_sku", "sql_type": "STRING", "comment": "Product SKU code", "is_dimension": true, "generation_expr": ""}},
        {{"name": "product_name", "sql_type": "STRING", "comment": "Human-readable product name", "is_dimension": true, "generation_expr": ""}},
        {{"name": "product_category", "sql_type": "STRING", "comment": "Product category", "is_dimension": true, "generation_expr": ""}},
        {{"name": "quantity", "sql_type": "INT", "comment": "Number of units ordered", "is_dimension": false, "generation_expr": "CAST(10 + FLOOR({{qty_noise}} * 100) AS INT)"}},
        {{"name": "unit_price", "sql_type": "DOUBLE", "comment": "Price per unit in USD", "is_dimension": false, "generation_expr": ""}},
        {{"name": "order_status", "sql_type": "STRING", "comment": "Order status: Delivered, Backorder, In Transit, or Cancelled", "is_dimension": true, "generation_expr": "CASE WHEN {{status_noise}} < 0.02 THEN 'Cancelled' WHEN {{status_noise}} < 0.05 THEN 'Backorder' WHEN {{status_noise}} < 0.08 THEN 'In Transit' ELSE 'Delivered' END"}}
      ],
      "seasonal_patterns": {{
        "Electronics": {{"11,12": 0.06}},
        "Clothing & Apparel": {{"3,4,9,10": 0.055}}
      }},
      "entity_dimension": "transaction",
      "dimension_values": [
        {{"sku": "SKU-EL-001", "name": "Wireless Bluetooth Speaker", "category": "Electronics", "price": 49.99}},
        {{"sku": "SKU-EL-003", "name": "USB-C Hub 7-in-1", "category": "Electronics", "price": 39.99}}
      ],
      "category_distribution": {{
        "Electronics": 0.025,
        "Food & Beverage": 0.035,
        "Clothing & Apparel": 0.02
      }}
    }}
  ],
  "metric_views": [
    {{
      "view_name": "shipment_orders_metrics",
      "source_table": "shipment_orders",
      "dimensions": [
        {{"name": "order_date", "expr": "order_date"}},
        {{"name": "product_category", "expr": "product_category"}}
      ],
      "measures": [
        {{"name": "total_revenue", "expr": "SUM(quantity * unit_price) FILTER (WHERE order_status = 'Delivered')", "comment": "Total revenue from delivered orders in USD"}},
        {{"name": "delivered_order_count", "expr": "COUNT(DISTINCT CASE WHEN order_status = 'Delivered' THEN order_id END)", "comment": "Number of successfully delivered orders"}},
        {{"name": "total_order_count", "expr": "COUNT(DISTINCT order_id)", "comment": "Total number of orders placed"}}
      ]
    }}
  ],
  "genie_instructions": "You are a supply chain analytics assistant for NorthStar Logistics...\\nWhen answering aggregation questions, prefer the metric views with MEASURE() syntax.",
  "sample_questions": [
    "Which SKUs are currently below their reorder point?",
    "What is the forecast accuracy by product category?"
  ],
  "example_sqls": [
    {{
      "question": "What is our fill rate by product category?",
      "sql_lines": ["SELECT product_category,\\n", "  MEASURE(fill_rate) AS fill_rate\\n", "FROM {{fqn}}.shipment_orders_metrics\\n", "GROUP BY ALL\\n", "ORDER BY fill_rate ASC"]
    }}
  ],
  "sql_snippets": {{
    "filters": [{{"sql": "orders.order_status = 'Delivered'", "display_name": "delivered orders", "synonyms": ["completed orders"], "instruction": "Use when calculating fill rate."}}],
    "expressions": [{{"alias": "order_month", "sql": "DATE_TRUNC('month', orders.order_date)", "display_name": "month", "synonyms": ["order month"]}}],
    "measures": [{{"alias": "total_revenue", "sql": "SUM(orders.quantity * orders.unit_price)", "display_name": "total revenue", "synonyms": ["revenue", "sales"]}}]
  }},
  "benchmarks": [
    {{
      "question": "What is our fill rate by product category?",
      "sql_lines": ["SELECT product_category,\\n", "  MEASURE(fill_rate) AS fill_rate\\n", "FROM {{fqn}}.shipment_orders_metrics\\n", "GROUP BY ALL\\n", "ORDER BY fill_rate ASC"]
    }}
  ]
}}
```

IMPORTANT: Keep the output compact to avoid truncation:
- SQL lines in example_sqls and benchmarks: use 1-3 lines per query, not one line per SQL clause
- dimension_values: include all {num_products} items but keep field names short
- Keep comments brief (under 60 chars)

Now generate the COMPLETE domain specification for the business context above. \
Return ONLY the JSON object — no markdown fences, no commentary."""


# ---------------------------------------------------------------------------
# Generation logic
# ---------------------------------------------------------------------------


def generate_domain_spec(
    spark: Any,
    industry: str,
    company_name: str,
    use_case: str,
    business_context: str,
    num_tables: int = 3,
    num_products: int = 20,
    num_locations: int = 8,
    endpoint: str = DEFAULT_LLM_ENDPOINT,
    workspace_client: Any = None,
) -> DomainSpec:
    """Generate a DomainSpec by calling the Foundation Model API."""

    ws = workspace_client or _default_workspace_client()

    user_prompt = USER_PROMPT_TEMPLATE.format(
        industry=industry,
        company_name=company_name,
        use_case=use_case,
        business_context=business_context,
        num_tables=num_tables,
        num_products=num_products,
        num_locations=num_locations,
    )

    current_max_tokens = LLM_MAX_TOKENS
    last_error = None
    for attempt in range(1 + LLM_MAX_RETRIES):
        try:
            _logger.info("LLM attempt %d/%d ...", attempt + 1, 1 + LLM_MAX_RETRIES)
            response = _api_request(
                ws,
                "POST",
                f"/serving-endpoints/{endpoint}/invocations",
                payload={
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    "max_tokens": current_max_tokens,
                    "temperature": LLM_TEMPERATURE,
                },
                timeout=LLM_TIMEOUT_SECONDS,
            )

            content = response["choices"][0]["message"]["content"]
            finish_reason = (
                response.get("choices", [{}])[0].get("finish_reason", "unknown")
            )

            # Strip markdown fences if present
            content = content.strip()
            fence_match = re.match(r'^```(?:\w+)?\s*\n(.*?)```\s*$', content, re.DOTALL)
            if fence_match:
                content = fence_match.group(1).strip()

            if finish_reason == "length":
                _logger.warning(
                    "Response truncated (finish_reason=length, %d chars). Retrying...",
                    len(content),
                )
                last_error = ValueError(
                    f"LLM response truncated at {len(content)} chars "
                    f"(finish_reason=length). Increase LLM_MAX_TOKENS."
                )
                if attempt < LLM_MAX_RETRIES:
                    current_max_tokens = min(int(current_max_tokens * 1.5), LLM_MAX_TOKENS_CAP)
                    continue
                raise last_error

            raw = json.loads(content)
            spec = _parse_domain_spec(raw)
            _validate_domain_spec(spec, num_tables, num_products, num_locations)
            _validate_generation_expressions(spec)
            return spec

        except Exception as exc:
            last_error = exc
            _logger.info("Attempt %d failed: %s", attempt + 1, exc)
            if attempt < LLM_MAX_RETRIES:
                continue

    raise RuntimeError(
        f"Failed to generate domain spec after {1 + LLM_MAX_RETRIES} attempts: {last_error}"
    )


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _parse_domain_spec(raw: dict) -> DomainSpec:
    """Parse a raw JSON dict into a DomainSpec."""

    tables = [_parse_table_spec(t) for t in raw["tables"]]
    metric_views = [_parse_metric_view_spec(mv) for mv in raw["metric_views"]]
    example_sqls = [
        ExampleSQL(question=e["question"], sql_lines=e["sql_lines"])
        for e in raw["example_sqls"]
    ]
    benchmarks = [
        BenchmarkSpec(question=b["question"], sql_lines=b["sql_lines"])
        for b in raw["benchmarks"]
    ]
    snippets_raw = raw["sql_snippets"]
    sql_snippets = SQLSnippets(
        filters=snippets_raw["filters"],
        expressions=snippets_raw["expressions"],
        measures=snippets_raw["measures"],
    )

    return DomainSpec(
        company_name=raw["company_name"],
        industry=raw["industry"],
        use_case=raw["use_case"],
        space_title=raw["space_title"],
        space_description=raw["space_description"],
        schema_basename=raw["schema_basename"],
        tables=tables,
        metric_views=metric_views,
        genie_instructions=raw["genie_instructions"],
        sample_questions=raw["sample_questions"],
        example_sqls=example_sqls,
        sql_snippets=sql_snippets,
        benchmarks=benchmarks,
    )


def _parse_table_spec(raw: dict) -> TableSpec:
    """Parse a raw table dict into a TableSpec."""

    columns = [
        ColumnSpec(
            name=c["name"],
            sql_type=c["sql_type"],
            comment=c["comment"],
            is_dimension=c["is_dimension"],
            generation_expr=c.get("generation_expr", ""),
        )
        for c in raw["columns"]
    ]
    table_name = sanitize_sql_identifier(raw["table_name"], "table_name")
    # Validate column names
    for col in columns:
        col.name = sanitize_sql_identifier(col.name, f"column in {table_name}")

    # Validate dimension value keys
    dim_values = raw.get("dimension_values", [])
    if dim_values:
        for dv in dim_values:
            sanitized = {}
            for k, v in dv.items():
                sanitized[sanitize_sql_identifier(k, f"dimension key in {table_name}")] = v
            dv.clear()
            dv.update(sanitized)

    return TableSpec(
        table_name=table_name,
        description=raw["description"],
        columns=columns,
        seasonal_patterns=raw.get("seasonal_patterns", {}),
        entity_dimension=raw.get("entity_dimension", "transaction"),
        dimension_values=dim_values,
        category_distribution=raw.get("category_distribution", {}),
    )


def _parse_metric_view_spec(raw: dict) -> MetricViewSpec:
    """Parse a raw metric view dict into a MetricViewSpec."""

    view_name = sanitize_sql_identifier(raw["view_name"], "view_name")
    return MetricViewSpec(
        view_name=view_name,
        source_table=raw["source_table"],
        dimensions=raw["dimensions"],
        measures=raw["measures"],
    )


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _validate_domain_spec(
    spec: DomainSpec,
    expected_tables: int,
    expected_products: int,
    expected_locations: int,
) -> None:
    """Validate that the domain spec meets constraints."""

    if len(spec.tables) != expected_tables:
        raise ValueError(
            f"Expected {expected_tables} tables, got {len(spec.tables)}"
        )

    if len(spec.metric_views) != expected_tables:
        raise ValueError(
            f"Expected {expected_tables} metric views, got {len(spec.metric_views)}"
        )

    if len(spec.sample_questions) != 7:
        raise ValueError(
            f"Expected 7 sample questions, got {len(spec.sample_questions)}"
        )

    if len(spec.example_sqls) != 7:
        raise ValueError(
            f"Expected 7 example SQLs, got {len(spec.example_sqls)}"
        )

    if len(spec.benchmarks) != 7:
        raise ValueError(
            f"Expected 7 benchmarks, got {len(spec.benchmarks)}"
        )

    if len(spec.sql_snippets.filters) != 3:
        raise ValueError(
            f"Expected 3 filters, got {len(spec.sql_snippets.filters)}"
        )

    if len(spec.sql_snippets.expressions) != 3:
        raise ValueError(
            f"Expected 3 expressions, got {len(spec.sql_snippets.expressions)}"
        )

    if len(spec.sql_snippets.measures) != 4:
        raise ValueError(
            f"Expected 4 measures, got {len(spec.sql_snippets.measures)}"
        )

    # Verify 3-5 example SQLs use MEASURE() (target: 4 MEASURE / 3 plain table)
    measure_examples = sum(
        1 for ex in spec.example_sqls
        if any("MEASURE(" in line for line in ex.sql_lines)
    )
    if measure_examples < 3:
        raise ValueError(
            f"At least 3 example SQLs must use MEASURE(), found {measure_examples}"
        )
    if measure_examples > 5:
        raise ValueError(
            f"At most 5 example SQLs should use MEASURE(), found {measure_examples}"
        )

    # Verify 3-5 benchmarks use MEASURE() (target: 4 MEASURE / 3 plain table)
    measure_benchmarks = sum(
        1 for b in spec.benchmarks
        if any("MEASURE(" in line for line in b.sql_lines)
    )
    if measure_benchmarks < 3:
        raise ValueError(
            f"At least 3 benchmarks must use MEASURE(), found {measure_benchmarks}"
        )
    if measure_benchmarks > 5:
        raise ValueError(
            f"At most 5 benchmarks should use MEASURE(), found {measure_benchmarks}"
        )

    # Verify metric view measures contain exactly one aggregate function.
    # Metric views only allow a single aggregate per measure — ratios like
    # SUM(x)/COUNT(y) must be split into separate measures.
    _AGG_FUNCS = ("SUM(", "COUNT(", "AVG(", "MIN(", "MAX(", "STDDEV(", "VARIANCE(")
    for mv in spec.metric_views:
        for m in mv.measures:
            expr = m.get("expr", "").upper()
            agg_count = sum(expr.count(func) for func in _AGG_FUNCS)
            if agg_count == 0:
                raise ValueError(
                    f"Metric view '{mv.view_name}' measure '{m.get('name')}' "
                    f"has no aggregate function: {m.get('expr')}"
                )
            if agg_count > 1:
                raise ValueError(
                    f"Metric view '{mv.view_name}' measure '{m.get('name')}' "
                    f"contains {agg_count} aggregate calls but metric views allow "
                    f"exactly one per measure. Split ratio measures into separate "
                    f"measures. Expression: {m.get('expr')}"
                )

    # Validate metric view dimension/measure references against source table columns
    table_columns_map = {
        t.table_name: {c.name for c in t.columns} for t in spec.tables
    }
    for mv in spec.metric_views:
        src_cols = table_columns_map.get(mv.source_table, set())
        if not src_cols:
            raise ValueError(
                f"Metric view '{mv.view_name}' references source table "
                f"'{mv.source_table}' which does not exist"
            )
        for dim in mv.dimensions:
            dim_expr = dim.get("expr", "")
            # If it's a bare column name, check it exists
            if dim_expr and re.match(r'^[a-z_][a-z0-9_]*$', dim_expr):
                if dim_expr not in src_cols:
                    raise ValueError(
                        f"Metric view '{mv.view_name}' dimension '{dim['name']}' "
                        f"references column '{dim_expr}' not in table '{mv.source_table}'. "
                        f"Available: {sorted(src_cols)}"
                    )
        for m in mv.measures:
            expr_upper = m.get("expr", "").upper()
            if any(kw in expr_upper for kw in ("SELECT ", "FROM ", " JOIN ")):
                raise ValueError(
                    f"Metric view '{mv.view_name}' measure '{m.get('name')}' "
                    f"contains a subquery. Measures must be single aggregate expressions."
                )

    for table in spec.tables:
        if not table.columns:
            raise ValueError(f"Table {table.table_name} has no columns")
        if not table.dimension_values:
            raise ValueError(f"Table {table.table_name} has no dimension_values")


def _validate_generation_expressions(spec: DomainSpec) -> None:
    """Validate that generation_expr values only reference available columns.

    Raises ValueError if any expression references invalid columns or uses
    forbidden aggregate functions, which triggers an LLM retry.
    """
    _FORBIDDEN_AGGS = ("SUM(", "COUNT(", "AVG(", "MIN(", "MAX(", "STDDEV(", "VARIANCE(")
    # Columns always available in the skeleton/filtered CTE
    _SKELETON_COLS = {"dt", "mo", "qty_noise", "status_noise", "select_noise", "id_seq"}

    errors: list[str] = []

    for table in spec.tables:
        entity_fields: set[str] = set()
        if table.dimension_values:
            entity_fields = set(table.dimension_values[0].keys())

        valid_cols = _SKELETON_COLS | entity_fields

        for col in table.columns:
            expr = col.generation_expr
            if not expr:
                # Empty expr means use entity field directly
                if col.name not in entity_fields:
                    errors.append(
                        f"Table '{table.table_name}', column '{col.name}': "
                        f"empty generation_expr but '{col.name}' is not an entity field. "
                        f"Entity fields: {sorted(entity_fields)}"
                    )
                continue

            # Simulate the placeholder substitution done in data.py
            test_expr = expr.upper()
            test_expr = test_expr.replace("{QTY_NOISE}", "QTY_NOISE")
            test_expr = test_expr.replace("{STATUS_NOISE}", "STATUS_NOISE")
            test_expr = test_expr.replace("{SELECT_NOISE}", "SELECT_NOISE")
            test_expr = test_expr.replace("{ID_SEQ}", "ID_SEQ")

            # Check for forbidden aggregate functions
            for agg in _FORBIDDEN_AGGS:
                if agg in test_expr:
                    errors.append(
                        f"Table '{table.table_name}', column '{col.name}': "
                        f"generation_expr uses forbidden aggregate '{agg.rstrip('(')}'. "
                        f"Expressions run per-row and cannot use aggregates. "
                        f"Expression: {expr}"
                    )

            # Validate column references — extract identifiers from the
            # expression and check that they exist in the skeleton CTE.
            # Strip e./d. prefixes, placeholders, and string literals first.
            ref_expr = expr
            ref_expr = re.sub(r"'(?:''|[^'])*'", "", ref_expr)  # strip strings
            ref_expr = re.sub(r"\{[a-z_]+\}", "", ref_expr)  # strip {placeholders}
            # Extract e.XXX and d.XXX references
            aliased_refs = re.findall(r'\b[ed]\.([a-z_][a-z0-9_]*)', ref_expr, re.IGNORECASE)
            for ref in aliased_refs:
                ref_lower = ref.lower()
                if ref_lower not in valid_cols:
                    errors.append(
                        f"Table '{table.table_name}', column '{col.name}': "
                        f"generation_expr references '{ref}' which is not a valid "
                        f"column. Available: {sorted(valid_cols)}. "
                        f"Expression: {expr}"
                    )

        # Check for forward references to other output columns in the same table.
        # In SQL SELECT, a column alias cannot reference another alias from the same SELECT.
        all_output_names = {c.name.lower() for c in table.columns}
        # Output column names that are NOT skeleton/entity columns (i.e., computed columns)
        computed_names = all_output_names - valid_cols

        for col in table.columns:
            expr = col.generation_expr
            if not expr:
                continue
            # Strip string literals and check for bare references to other computed columns
            stripped = re.sub(r"'(?:''|[^'])*'", "", expr)
            stripped = re.sub(r"\{[a-z_]+\}", "", stripped)
            # Find bare identifiers (not prefixed by e. or d.)
            bare_ids = set(re.findall(r'(?<![.a-z_])\b([a-z_][a-z0-9_]*)\b', stripped, re.IGNORECASE))
            # Remove SQL keywords and known functions
            _SQL_NOISE = {"case", "when", "then", "else", "end", "and", "or", "not", "in",
                          "as", "is", "null", "true", "false", "cast", "round", "abs",
                          "concat", "lpad", "substring", "trim", "upper", "lower",
                          "coalesce", "nullif", "greatest", "least", "if", "iff",
                          "date_format", "date_trunc", "month", "dayofweek", "row_number",
                          "over", "order", "by", "string", "int", "double", "decimal",
                          "between", "like", "select", "from", "where", "distinct",
                          "filter", "asc", "desc", "rows", "preceding", "following",
                          "current", "row", "unbounded"}
            bare_ids -= _SQL_NOISE
            bare_ids -= valid_cols  # skeleton + entity fields are valid
            bare_ids -= {col.name.lower()}  # a column can reference itself conceptually (shouldn't but not a forward ref)
            # Check if any remaining bare id is a computed output column name
            forward_refs = bare_ids & computed_names
            if forward_refs:
                errors.append(
                    f"Table '{table.table_name}', column '{col.name}': "
                    f"expression references other computed column(s) {sorted(forward_refs)} "
                    f"which is a forward reference (not available in the same SELECT). "
                    f"Use the underlying noise/entity columns instead. Expression: {expr}"
                )

    if errors:
        raise ValueError(
            "Invalid generation expressions (will retry with LLM):\n"
            + "\n".join(f"  - {e}" for e in errors)
        )
