"""Manufacturing subindustry use cases sourced from FY27 Genie SWAT prioritization."""

SUBINDUSTRIES = [
    "Automotive",
    "Semiconductor",
    "Computer & Electronic",
    "Logistics",
    "Chemicals & Materials",
    "Machinery",
    "Oil & Gas Integrated",
    "Oil & Gas Refining",
    "Oil & Gas Midstream",
    "Oil & Gas Upstream",
    "Electric Utility",
    "Aerospace",
    "Power Generation",
    "Industrial Distribution",
    "Railroad",
    "Mining",
    "Food & Beverage",
    "Construction & Engineering",
]

USE_CASES: dict[str, list[dict[str, str | int]]] = {
    "Automotive": [
        {"label": "Vehicle Recall Root Cause Analysis", "use_case": "Vehicle recall root cause analysis and defect pattern identification", "importance": 10},
        {"label": "Vehicle Health & Maintenance Report", "use_case": "Connected vehicle health monitoring and predictive maintenance reporting", "importance": 9},
        {"label": "Product Feature Usage Analytics", "use_case": "In-vehicle feature adoption tracking and customer usage pattern analytics", "importance": 9},
        {"label": "Design Space Simulation for Safety", "use_case": "Design space exploration and simulation for vehicle safety optimization", "importance": 9},
    ],
    "Semiconductor": [
        {"label": "Quality Event Root Cause Analysis", "use_case": "Semiconductor quality event root cause analysis and yield improvement", "importance": 10},
        {"label": "Design Space Simulation", "use_case": "Chip design space exploration and process parameter simulation", "importance": 10},
        {"label": "Virtual Metrology Defect Detection", "use_case": "Virtual metrology and inline defect detection for wafer fabrication", "importance": 10},
        {"label": "Demand Forecasting", "use_case": "Semiconductor demand forecasting and order backlog management", "importance": 9},
        {"label": "Salable Inventory Optimization", "use_case": "Salable inventory optimization across wafer and die stock", "importance": 9},
        {"label": "Supply & Materials Capacity Allocation", "use_case": "Supply and materials capacity allocation across fab facilities", "importance": 9},
        {"label": "Financial Analytics & Reporting", "use_case": "Semiconductor financial analytics, margin analysis, and cost reporting", "importance": 5},
    ],
    "Computer & Electronic": [
        {"label": "Visual Defect Detection", "use_case": "Visual defect detection and classification in electronics manufacturing", "importance": 10},
        {"label": "Predictive Maintenance Troubleshoot", "use_case": "Predictive maintenance and equipment troubleshooting for electronics assembly", "importance": 9},
        {"label": "Design Space Simulation System on Chip", "use_case": "System-on-chip design space simulation and performance optimization", "importance": 9},
    ],
    "Logistics": [
        {"label": "Route Planning", "use_case": "Route planning optimization for freight and last-mile delivery", "importance": 10},
        {"label": "Fleet Planning and Optimization", "use_case": "Fleet planning, vehicle allocation, and capacity optimization", "importance": 9},
        {"label": "Load Demand Forecasting", "use_case": "Load demand forecasting and shipment volume prediction", "importance": 9},
    ],
    "Chemicals & Materials": [
        {"label": "Demand Forecasting", "use_case": "Chemical product demand forecasting and production planning", "importance": 10},
        {"label": "Autonomous Lab Experiments", "use_case": "Autonomous lab experiment tracking and formulation optimization", "importance": 10},
        {"label": "Quality Event Root Cause Analysis", "use_case": "Chemical process quality event root cause analysis and batch deviation tracking", "importance": 9},
        {"label": "Product & Process Traceability", "use_case": "Product and process traceability across chemical production batches", "importance": 9},
    ],
    "Machinery": [
        {"label": "Asset Health", "use_case": "Industrial machinery asset health monitoring and failure prediction", "importance": 10},
        {"label": "Machining Process Defect Detection", "use_case": "Machining process defect detection and tool wear analysis", "importance": 10},
        {"label": "Production Monitoring", "use_case": "Production line monitoring, OEE tracking, and throughput optimization", "importance": 10},
        {"label": "Field Service Assistant", "use_case": "Field service technician dispatch optimization and repair analytics", "importance": 9},
        {"label": "Quality Event Root Cause Analysis", "use_case": "Machinery quality event root cause analysis and corrective action tracking", "importance": 9},
        {"label": "Demand Forecasting", "use_case": "Industrial equipment demand forecasting and order pipeline management", "importance": 9},
        {"label": "Spare Part Inventory Optimization", "use_case": "Spare part inventory optimization and service level management", "importance": 9},
        {"label": "Manufacturing Resource Planning", "use_case": "Manufacturing resource planning, scheduling, and capacity utilization", "importance": 9},
        {"label": "Working Capital & Cash Flow Optimization", "use_case": "Working capital optimization and cash flow forecasting for machinery operations", "importance": 7},
        {"label": "Financial Analytics & Reporting", "use_case": "Financial analytics, cost center reporting, and margin analysis for machinery", "importance": 6},
        {"label": "Spend Intelligence", "use_case": "Procurement spend intelligence and supplier performance analytics", "importance": 5},
    ],
    "Oil & Gas Integrated": [
        {"label": "Predictive Maintenance & Asset Health", "use_case": "Predictive maintenance and asset health monitoring for integrated oil and gas operations", "importance": 10},
        {"label": "Production Monitoring & Control Center", "use_case": "Production monitoring and control center analytics for integrated O&G facilities", "importance": 10},
        {"label": "Scenario Planning & Business Simulation", "use_case": "Scenario planning and business simulation for integrated oil and gas operations", "importance": 9},
        {"label": "Capital Investment Simulation", "use_case": "Capital investment simulation and project portfolio optimization", "importance": 9},
        {"label": "Financial Analytics & Reporting", "use_case": "Financial analytics and reporting for integrated oil and gas operations", "importance": 6},
        {"label": "Working Capital & Cash Flow Optimization", "use_case": "Working capital and cash flow optimization for integrated O&G", "importance": 6},
    ],
    "Oil & Gas Refining": [
        {"label": "Predictive Maintenance & Asset Health", "use_case": "Predictive maintenance and asset health for refinery equipment and process units", "importance": 10},
        {"label": "Quality Event Root Cause Analysis", "use_case": "Refinery quality event root cause analysis and process deviation tracking", "importance": 9},
        {"label": "Energy Use Monitoring Heat", "use_case": "Energy use monitoring and heat integration optimization for refinery operations", "importance": 9},
        {"label": "Production Monitoring", "use_case": "Refinery production monitoring, throughput tracking, and yield optimization", "importance": 9},
        {"label": "Financial Analytics & Reporting", "use_case": "Financial analytics and reporting for refining operations", "importance": 6},
        {"label": "Working Capital & Cash Flow Optimization", "use_case": "Working capital and cash flow optimization for refining operations", "importance": 6},
    ],
    "Oil & Gas Midstream": [
        {"label": "Logistics Optimization", "use_case": "Pipeline and terminal logistics optimization for midstream operations", "importance": 10},
        {"label": "Regulation & Compliance", "use_case": "Regulatory compliance tracking and reporting for midstream operations", "importance": 9},
        {"label": "Scenario Planning & Business Simulation", "use_case": "Scenario planning and business simulation for midstream pipeline networks", "importance": 9},
        {"label": "Energy Trading", "use_case": "Energy trading analytics, position tracking, and market risk management", "importance": 9},
        {"label": "Financial Analytics & Reporting", "use_case": "Financial analytics and reporting for midstream operations", "importance": 8},
        {"label": "Automated Reporting of Carbon Intensity", "use_case": "Automated carbon intensity reporting and emissions tracking for midstream", "importance": 7},
        {"label": "Working Capital & Cash Flow Optimization", "use_case": "Working capital and cash flow optimization for midstream operations", "importance": 6},
        {"label": "Spend Intelligence", "use_case": "Procurement spend intelligence and vendor management for midstream", "importance": 5},
    ],
    "Oil & Gas Upstream": [
        {"label": "Predictive Maintenance & Asset Health", "use_case": "Predictive maintenance and asset health for upstream drilling and production equipment", "importance": 10},
        {"label": "Reservoir Management", "use_case": "Reservoir performance management and production optimization", "importance": 9},
        {"label": "Well Production Monitoring & Flow", "use_case": "Well production monitoring, flow rate analysis, and decline curve tracking", "importance": 9},
    ],
    "Electric Utility": [
        {"label": "Transformer Asset Health", "use_case": "Power transformer asset health monitoring and failure risk scoring", "importance": 10},
        {"label": "Grid Management & Energy Mix", "use_case": "Grid management, energy mix optimization, and load balancing analytics", "importance": 10},
        {"label": "Demand Forecasting", "use_case": "Electric utility demand forecasting and load prediction", "importance": 9},
        {"label": "Outage Response", "use_case": "Outage response management, crew dispatch, and restoration time analytics", "importance": 9},
    ],
    "Aerospace": [
        {"label": "Predictive Maintenance & Asset Health", "use_case": "Predictive maintenance and asset health for aerospace engines and airframes", "importance": 10},
        {"label": "Design Space Simulation for Fuel Efficiency", "use_case": "Design space simulation for aerodynamic and fuel efficiency optimization", "importance": 10},
        {"label": "Quality Event Root Cause Analysis", "use_case": "Aerospace quality event root cause analysis and non-conformance tracking", "importance": 9},
        {"label": "Demand Forecasting", "use_case": "Aerospace parts and aftermarket demand forecasting", "importance": 9},
        {"label": "Supply & Materials Planning", "use_case": "Aerospace supply chain and materials planning for long-lead components", "importance": 9},
        {"label": "Product Traceability Anti-counterfeit", "use_case": "Product traceability and anti-counterfeit verification for aerospace components", "importance": 9},
        {"label": "Working Capital & Cash Flow Optimization", "use_case": "Working capital and cash flow optimization for aerospace programs", "importance": 6},
        {"label": "Financial Analytics & Reporting", "use_case": "Financial analytics and program cost reporting for aerospace", "importance": 5},
    ],
    "Power Generation": [
        {"label": "Grid Management & Energy Mix", "use_case": "Power generation grid management and energy portfolio mix optimization", "importance": 10},
        {"label": "Outage Response", "use_case": "Power plant outage management, scheduling, and restoration analytics", "importance": 10},
        {"label": "Nuclear Safety", "use_case": "Nuclear safety monitoring, inspection tracking, and regulatory compliance analytics", "importance": 10},
        {"label": "Hydro Optimization", "use_case": "Hydroelectric generation optimization and water resource management", "importance": 9},
        {"label": "Solar Optimization Behind the Meter", "use_case": "Behind-the-meter solar generation optimization and battery storage analytics", "importance": 9},
        {"label": "Wind Optimization", "use_case": "Wind farm generation optimization, turbine performance, and wake analysis", "importance": 9},
        {"label": "Financial Analytics & Reporting", "use_case": "Financial analytics and reporting for power generation assets", "importance": 5},
    ],
    "Industrial Distribution": [
        {"label": "Demand Forecasting", "use_case": "Industrial distribution demand forecasting and replenishment planning", "importance": 10},
        {"label": "Inventory Optimization", "use_case": "Warehouse inventory optimization and service level management for industrial distribution", "importance": 9},
        {"label": "Working Capital & Cash Flow Optimization", "use_case": "Working capital and cash flow optimization for industrial distribution", "importance": 5},
    ],
    "Railroad": [
        {"label": "Route Planning", "use_case": "Railroad route planning, network optimization, and consist management", "importance": 10},
        {"label": "Predictive Maintenance & Asset Health", "use_case": "Predictive maintenance and asset health for rolling stock and track infrastructure", "importance": 9},
        {"label": "Freight Demand Forecasting", "use_case": "Freight demand forecasting and carload volume prediction", "importance": 9},
    ],
    "Mining": [
        {"label": "Haul Vehicle Asset Health", "use_case": "Mining haul vehicle asset health monitoring and fleet reliability analytics", "importance": 10},
        {"label": "Production Monitoring & Control Center", "use_case": "Mine production monitoring, ore grade tracking, and processing throughput analytics", "importance": 9},
    ],
    "Food & Beverage": [
        {"label": "Quality Event Root Cause Analysis", "use_case": "Food safety quality event root cause analysis and HACCP compliance tracking", "importance": 10},
        {"label": "Product & Process Traceability Recall", "use_case": "Product and process traceability for recall management and lot tracking", "importance": 10},
        {"label": "Inventory Optimization", "use_case": "Perishable inventory optimization and shelf-life management", "importance": 9},
        {"label": "Scenario Planning & Business Simulation", "use_case": "Scenario planning and business simulation for food and beverage operations", "importance": 9},
    ],
    "Construction & Engineering": [
        {"label": "Engineering Bid Creation", "use_case": "Engineering bid creation, cost estimation, and proposal analytics", "importance": 10},
        {"label": "Production and Project Completion Monitoring", "use_case": "Construction project completion monitoring, milestone tracking, and resource utilization", "importance": 9},
    ],
}

